
services:
  - docker
  
before_install:
  - docker build -t qgis_dev .
  
  - docker run -d -p 127.0.0.1:80:4567 qgis_dev /bin/sh -c "ls; find . -name "python-qgis""
  - docker ps -a
  - docker run qgis_dev /bin/sh -c "ls; find . -name "python-qgis""

script:
  - ls