language: minimal

stages:
  - build
  - test

do_test: &do_test
  stage: test
  services:
    - docker
  install: 
    - docker pull ubuntu:trusty
    # - docker build -t qgis_dev .
    # - docker run -d -p 127.0.0.1:80:4567 qgis_dev /bin/bash -c "ls;"
    # - docker ps -a
  script: 
    - docker run --env-file=env-here.env ubuntu /bin/bash -c "echo $APP_ID - $APP_CODE; cd /xyz_qgis_plugin; source runTest.sh test/test_basemap.py"
    - docker run --env-file=env-here.env ubuntu /bin/bash -c "cd /xyz_qgis_plugin; source runTest.sh test/test_con.py"

jobs:
  include:
    - stage: build
      script: echo build source makeBuild.sh 1.5.6
    - <<: *do_test