language: minimal

stages:
  - build
  - test

do_test: &do_test
  stage: test
  services:
    - docker
  install: 
    - echo docker build -t qgis_dev .
    # - docker run -d -p 127.0.0.1:80:4567 qgis_dev /bin/bash -c "ls;"
    # - docker ps -a
  script: 
    - echo $TEST docker run qgis_dev /bin/bash -c "cd /xyz_qgis_plugin; source runTest.sh test/$TEST"
jobs:
  include:
    - stage: build
      script: echo build source makeBuild.sh 1.5.6
    - <<: *do_test
      env: TEST=test_basemap.py
    - <<: *do_test
      env: TEST=test_con.py